### ISSUE TITLE
Modify User Entity

### ISSUE THREAD

**Issue by dFarras** [dFarras/real-estate-api#2]
Present user does not match to defined data model, we need to modify it to apply to it.

Attributes
-String fiscalId (NIF) [Primary key]
-String name
[ADDED] -String password
-String username
-String email

After this modification, and in order to be able to compile, we need to also change classes: UserService and UserController

**Comment by ManuRamirez** [comment]
I think we need a new attribute Password

**Comment by dFarras** [comment]
Sure! I'm adding it to issue description
